using JobBoard.Data.Entities;
using JobBoard.Infrastructure.context;

namespace JobBoard.Core.Seeders
{
	public static class CountrySeeder
	{
		private static List<Country> GetAllCountries()
		{
			return new List<Country>
		{
			new Country { CountryId = 1, CountryName = "Afghanistan" },
			new Country { CountryId = 2, CountryName = "Albania" },
			new Country { CountryId = 3, CountryName = "Algeria" },
			new Country { CountryId = 4, CountryName = "Andorra" },
			new Country { CountryId = 5, CountryName = "Angola" },
			new Country { CountryId = 6, CountryName = "Antigua and Barbuda" },
			new Country { CountryId = 7, CountryName = "Argentina" },
			new Country { CountryId = 8, CountryName = "Armenia" },
			new Country { CountryId = 9, CountryName = "Australia" },
			new Country { CountryId = 10, CountryName = "Austria" },
			new Country { CountryId = 11, CountryName = "Azerbaijan" },
			new Country { CountryId = 12, CountryName = "Bahamas" },
			new Country { CountryId = 13, CountryName = "Bahrain" },
			new Country { CountryId = 14, CountryName = "Bangladesh" },
			new Country { CountryId = 15, CountryName = "Barbados" },
			new Country { CountryId = 16, CountryName = "Belarus" },
			new Country { CountryId = 17, CountryName = "Belgium" },
			new Country { CountryId = 18, CountryName = "Belize" },
			new Country { CountryId = 19, CountryName = "Benin" },
			new Country { CountryId = 20, CountryName = "Bhutan" },
			new Country { CountryId = 21, CountryName = "Bolivia" },
			new Country { CountryId = 22, CountryName = "Bosnia and Herzegovina" },
			new Country { CountryId = 23, CountryName = "Botswana" },
			new Country { CountryId = 24, CountryName = "Brazil" },
			new Country { CountryId = 25, CountryName = "Brunei" },
			new Country { CountryId = 26, CountryName = "Bulgaria" },
			new Country { CountryId = 27, CountryName = "Burkina Faso" },
			new Country { CountryId = 28, CountryName = "Burundi" },
			new Country { CountryId = 29, CountryName = "Cabo Verde" },
			new Country { CountryId = 30, CountryName = "Cambodia" },
			new Country { CountryId = 31, CountryName = "Cameroon" },
			new Country { CountryId = 32, CountryName = "Canada" },
			new Country { CountryId = 33, CountryName = "Central African Republic" },
			new Country { CountryId = 34, CountryName = "Chad" },
			new Country { CountryId = 35, CountryName = "Chile" },
			new Country { CountryId = 36, CountryName = "China" },
			new Country { CountryId = 37, CountryName = "Colombia" },
			new Country { CountryId = 38, CountryName = "Comoros" },
			new Country { CountryId = 39, CountryName = "Congo (Congo-Brazzaville)" },
			new Country { CountryId = 40, CountryName = "Costa Rica" },
			new Country { CountryId = 41, CountryName = "Croatia" },
			new Country { CountryId = 42, CountryName = "Cuba" },
			new Country { CountryId = 43, CountryName = "Cyprus" },
			new Country { CountryId = 44, CountryName = "Czechia (Czech Republic)" },
			new Country { CountryId = 45, CountryName = "Democratic Republic of the Congo" },
			new Country { CountryId = 46, CountryName = "Denmark" },
			new Country { CountryId = 47, CountryName = "Djibouti" },
			new Country { CountryId = 48, CountryName = "Dominica" },
			new Country { CountryId = 49, CountryName = "Dominican Republic" },
			new Country { CountryId = 50, CountryName = "Ecuador" },
			new Country { CountryId = 51, CountryName = "Egypt" },
			new Country { CountryId = 52, CountryName = "El Salvador" },
			new Country { CountryId = 53, CountryName = "Equatorial Guinea" },
			new Country { CountryId = 54, CountryName = "Eritrea" },
			new Country { CountryId = 55, CountryName = "Estonia" },
			new Country { CountryId = 56, CountryName = "Eswatini (fmr. \"Swaziland\")" },
			new Country { CountryId = 57, CountryName = "Ethiopia" },
			new Country { CountryId = 58, CountryName = "Fiji" },
			new Country { CountryId = 59, CountryName = "Finland" },
			new Country { CountryId = 60, CountryName = "France" },
			new Country { CountryId = 61, CountryName = "Gabon" },
			new Country { CountryId = 62, CountryName = "Gambia" },
			new Country { CountryId = 63, CountryName = "Georgia" },
			new Country { CountryId = 64, CountryName = "Germany" },
			new Country { CountryId = 65, CountryName = "Ghana" },
			new Country { CountryId = 66, CountryName = "Greece" },
			new Country { CountryId = 67, CountryName = "Grenada" },
			new Country { CountryId = 68, CountryName = "Guatemala" },
			new Country { CountryId = 69, CountryName = "Guinea" },
			new Country { CountryId = 70, CountryName = "Guinea-Bissau" },
			new Country { CountryId = 71, CountryName = "Guyana" },
			new Country { CountryId = 72, CountryName = "Haiti" },
			new Country { CountryId = 73, CountryName = "Holy See" },
			new Country { CountryId = 74, CountryName = "Honduras" },
			new Country { CountryId = 75, CountryName = "Hungary" },
			new Country { CountryId = 76, CountryName = "Iceland" },
			new Country { CountryId = 77, CountryName = "India" },
			new Country { CountryId = 78, CountryName = "Indonesia" },
			new Country { CountryId = 79, CountryName = "Iran" },
			new Country { CountryId = 80, CountryName = "Iraq" },
			new Country { CountryId = 81, CountryName = "Ireland" },
			new Country { CountryId = 82, CountryName = "Israel" },
			new Country { CountryId = 83, CountryName = "Italy" },
			new Country { CountryId = 84, CountryName = "Jamaica" },
			new Country { CountryId = 85, CountryName = "Japan" },
			new Country { CountryId = 86, CountryName = "Jordan" },
			new Country { CountryId = 87, CountryName = "Kazakhstan" },
			new Country { CountryId = 88, CountryName = "Kenya" },
			new Country { CountryId = 89, CountryName = "Kiribati" },
			new Country { CountryId = 90, CountryName = "Kuwait" },
			new Country { CountryId = 91, CountryName = "Kyrgyzstan" },
			new Country { CountryId = 92, CountryName = "Laos" },
			new Country { CountryId = 93, CountryName = "Latvia" },
			new Country { CountryId = 94, CountryName = "Lebanon" },
			new Country { CountryId = 95, CountryName = "Lesotho" },
			new Country { CountryId = 96, CountryName = "Liberia" },
			new Country { CountryId = 97, CountryName = "Libya" },
			new Country { CountryId = 98, CountryName = "Liechtenstein" },
			new Country { CountryId = 99, CountryName = "Lithuania" },
			new Country { CountryId = 100, CountryName = "Luxembourg" },
			new Country { CountryId = 101, CountryName = "Madagascar" },
			new Country { CountryId = 102, CountryName = "Malawi" },
			new Country { CountryId = 103, CountryName = "Malaysia" },
			new Country { CountryId = 104, CountryName = "Maldives" },
			new Country { CountryId = 105, CountryName = "Mali" },
			new Country { CountryId = 106, CountryName = "Malta" },
			new Country { CountryId = 107, CountryName = "Marshall Islands" },
			new Country { CountryId = 108, CountryName = "Mauritania" },
			new Country { CountryId = 109, CountryName = "Mauritius" },
			new Country { CountryId = 110, CountryName = "Mexico" },
			new Country { CountryId = 111, CountryName = "Micronesia" },
			new Country { CountryId = 112, CountryName = "Moldova" },
			new Country { CountryId = 113, CountryName = "Monaco" },
			new Country { CountryId = 114, CountryName = "Mongolia" },
			new Country { CountryId = 115, CountryName = "Montenegro" },
			new Country { CountryId = 116, CountryName = "Morocco" },
			new Country { CountryId = 117, CountryName = "Mozambique" },
			new Country { CountryId = 118, CountryName = "Myanmar (formerly Burma)" },
			new Country { CountryId = 119, CountryName = "Namibia" },
			new Country { CountryId = 120, CountryName = "Nauru" },
			new Country { CountryId = 121, CountryName = "Nepal" },
			new Country { CountryId = 122, CountryName = "Netherlands" },
			new Country { CountryId = 123, CountryName = "New Zealand" },
			new Country { CountryId = 124, CountryName = "Nicaragua" },
			new Country { CountryId = 125, CountryName = "Niger" },
			new Country { CountryId = 126, CountryName = "Nigeria" },
			new Country { CountryId = 127, CountryName = "North Korea" },
			new Country { CountryId = 128, CountryName = "North Macedonia" },
			new Country { CountryId = 129, CountryName = "Norway" },
			new Country { CountryId = 130, CountryName = "Oman" },
			new Country { CountryId = 131, CountryName = "Pakistan" },
			new Country { CountryId = 132, CountryName = "Palau" },
			new Country { CountryId = 133, CountryName = "Palestine State" },
			new Country { CountryId = 134, CountryName = "Panama" },
			new Country { CountryId = 135, CountryName = "Papua New Guinea" },
			new Country { CountryId = 136, CountryName = "Paraguay" },
			new Country { CountryId = 137, CountryName = "Peru" },
			new Country { CountryId = 138, CountryName = "Philippines" },
			new Country { CountryId = 139, CountryName = "Poland" },
			new Country { CountryId = 140, CountryName = "Portugal" },
			new Country { CountryId = 141, CountryName = "Qatar" },
			new Country { CountryId = 142, CountryName = "Romania" },
			new Country { CountryId = 143, CountryName = "Russia" },
			new Country { CountryId = 144, CountryName = "Rwanda" },
			new Country { CountryId = 145, CountryName = "Saint Kitts and Nevis" },
			new Country { CountryId = 146, CountryName = "Saint Lucia" },
			new Country { CountryId = 147, CountryName = "Saint Vincent and the Grenadines" },
			new Country { CountryId = 148, CountryName = "Samoa" },
			new Country { CountryId = 149, CountryName = "San Marino" },
			new Country { CountryId = 150, CountryName = "Sao Tome and Principe" },
			new Country { CountryId = 151, CountryName = "Saudi Arabia" },
			new Country { CountryId = 152, CountryName = "Senegal" },
			new Country { CountryId = 153, CountryName = "Serbia" },
			new Country { CountryId = 154, CountryName = "Seychelles" },
			new Country { CountryId = 155, CountryName = "Sierra Leone" },
			new Country { CountryId = 156, CountryName = "Singapore" },
			new Country { CountryId = 157, CountryName = "Slovakia" },
			new Country { CountryId = 158, CountryName = "Slovenia" },
			new Country { CountryId = 159, CountryName = "Solomon Islands" },
			new Country { CountryId = 160, CountryName = "Somalia" },
			new Country { CountryId = 161, CountryName = "South Africa" },
			new Country { CountryId = 162, CountryName = "South Korea" },
			new Country { CountryId = 163, CountryName = "South Sudan" },
			new Country { CountryId = 164, CountryName = "Spain" },
			new Country { CountryId = 165, CountryName = "Sri Lanka" },
			new Country { CountryId = 166, CountryName = "Sudan" },
			new Country { CountryId = 167, CountryName = "Suriname" },
			new Country { CountryId = 168, CountryName = "Sweden" },
			new Country { CountryId = 169, CountryName = "Switzerland" },
			new Country { CountryId = 170, CountryName = "Syria" },
			new Country { CountryId = 171, CountryName = "Tajikistan" },
			new Country { CountryId = 172, CountryName = "Tanzania" },
			new Country { CountryId = 173, CountryName = "Thailand" },
			new Country { CountryId = 174, CountryName = "Timor-Leste" },
			new Country { CountryId = 175, CountryName = "Togo" },
			new Country { CountryId = 176, CountryName = "Tonga" },
			new Country { CountryId = 177, CountryName = "Trinidad and Tobago" },
			new Country { CountryId = 178, CountryName = "Tunisia" },
			new Country { CountryId = 179, CountryName = "Turkey" },
			new Country { CountryId = 180, CountryName = "Turkmenistan" },
			new Country { CountryId = 181, CountryName = "Tuvalu" },
			new Country { CountryId = 182, CountryName = "Uganda" },
			new Country { CountryId = 183, CountryName = "Ukraine" },
			new Country { CountryId = 184, CountryName = "United Arab Emirates" },
			new Country { CountryId = 185, CountryName = "United Kingdom" },
			new Country { CountryId = 186, CountryName = "United States of America" },
			new Country { CountryId = 187, CountryName = "Uruguay" },
			new Country { CountryId = 188, CountryName = "Uzbekistan" },
			new Country { CountryId = 189, CountryName = "Vanuatu" },
			new Country { CountryId = 190, CountryName = "Venezuela" },
			new Country { CountryId = 191, CountryName = "Vietnam" },
			new Country { CountryId = 192, CountryName = "Yemen" },
			new Country { CountryId = 193, CountryName = "Zambia" },
			new Country { CountryId = 194, CountryName = "Zimbabwe" }
		};
		}


		public static async Task SeedAsnyc(appDbContext context)
		{
			if (!context.countries.Any())
			{
				await context.countries.AddRangeAsync(GetAllCountries());
				await context.SaveChangesAsync();
			}
		}
	}

}
